lang/python: Initial inclusion of python-mako
snekpit/main pull request #54
Opened 2023-03-21 20:28 UTC by joebonrichie

Initially included for the mesa build

2023-03-22 20:18 UTC, ikeycode commented
I like - and it highlights the need to get automatic python dependencies working in boulder.
(Obviously just need that `monitoring.yml` and I'll merge)

2023-03-23 16:48 UTC, ReillyBrogan requested changes

2023-03-23 16:48 UTC, ReillyBrogan commented on lang/python/python-mako/monitoring.yml
> +    id: 97183
I think the actual ID is `3915`. ([ref](https://release-monitoring.org/project/3915/))

97183 seems to be [this](https://release-monitoring.org/project/97183/)

2023-03-23 18:04 UTC, ReillyBrogan commented
LGTM, I'm going to add the CPE after merging it

2023-03-23 18:04 UTC, merged